- hosts: hsrv
#    user: mammoth
  tasks:
    - name: nginx install
      become: yes
      apt: name=nginx-full update_cache=yes
        #apt update && apt install nginx-full
#update_cache: yes
#    - name: nginx remove
#      become: yes
#      apt: name=nginx-full state=absent
