- hosts: all
#    user: mammoth
  tasks:
    - name: update apt cache
      apt: 
          update_cache: yes
      tags:
          - updcache
      become: yes
        #apt update && apt install nginx-full
#update_cache: yes
