---
- name: retrieve the list of home directories
  command: ls -1 /home
  register: home_dirs
  changed_when: false
  check_mode: no

- name: Create tmux directory
  become: yes
  file: path=/home/{{ tmux_users }}/.tmux/ state=directory owner=mammoth group=mammoth mode=0755

- name: ensure tmux plugin directory exists
  become: yes
  file:
    path: "/home/{{ item }}/.tmux/plugins"
    state: directory
    recurse: yes
  become: yes
  become_user: "{{ item }}"
  when: item in home_dirs.stdout_lines
  with_items: "{{ tmux_users }}"

- name: ensure tmux plugin manager is installed
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "/home/{{ item }}/.tmux/plugins/tpm"
    version: master
  #  become: yes
  become_user: "{{ item }}"
  when: item in home_dirs.stdout_lines
  with_items: "{{ tmux_users }}"

- name: ensure tmux-continuum is installed
  git:
    repo: https://github.com/tmux-plugins/tmux-continuum
    dest: "/home/{{ item }}/.tmux/plugins/tmux-continuum"
    version: master
  with_items: "{{ tmux_users }}"

- name: ensure tmux-continuum is installed
  git:
    repo: https://github.com/tmux-plugins/tmux-resurrect
    dest: "/home/{{ item }}/.tmux/plugins/tmux-resurrect"
    version: master
  with_items: "{{ tmux_users }}"


- name: ensure tmux configuration is installed
  template:
    src: tmux.conf.j2
    dest: "/home/{{ item }}/.tmux/global.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  when: item in home_dirs.stdout_lines
  with_items: "{{ tmux_users }}"

- name: ensure tmux configuration is loaded
  lineinfile:
    dest: "/home/{{ item }}/.tmux.conf"
    line: "source ~/.tmux/global.conf"
    create: yes
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  when: item in home_dirs.stdout_lines
  with_items: "{{ tmux_users }}"
